"""empty message

Revision ID: b983a83b512f
Revises: 
Create Date: 2026-02-08 17:43:07.552917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b983a83b512f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('availability', sa.String(length=100), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('help_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abuse_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('help_request_id', sa.Integer(), nullable=False),
    sa.Column('abuse_type', sa.String(length=255), nullable=True),
    sa.Column('ongoing', sa.Boolean(), nullable=True),
    sa.Column('immediate_danger', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['help_request_id'], ['help_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('help_request_id')
    )
    op.create_table('human_rights_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('help_request_id', sa.Integer(), nullable=False),
    sa.Column('violation_type', sa.String(length=255), nullable=True),
    sa.Column('incident_date', sa.Date(), nullable=True),
    sa.Column('reported_party', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['help_request_id'], ['help_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('help_request_id')
    )
    op.create_table('mental_health_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('help_request_id', sa.Integer(), nullable=False),
    sa.Column('concern_type', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('preferred_contact', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['help_request_id'], ['help_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('help_request_id')
    )
    op.create_table('wellness_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('help_request_id', sa.Integer(), nullable=False),
    sa.Column('focus_area', sa.String(length=255), nullable=True),
    sa.Column('preferred_guidance', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['help_request_id'], ['help_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('help_request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wellness_details')
    op.drop_table('mental_health_details')
    op.drop_table('human_rights_reports')
    op.drop_table('abuse_reports')
    op.drop_table('help_requests')
    op.drop_table('volunteers')
    op.drop_table('services')
    # ### end Alembic commands ###
